import localFont from "next/font/local";
import "./globals.css";
import Hero from "@/components/Hero/Hero";
import Travel from "@/components/Travel/Travel";
import { Urbanist } from "next/font/google";
import Illustration1 from "@/components/card-illustrator/Illustration1";
import Influencer from "@/components/Influencer/Influencer";
import Sticky from "@/components/Sticky/Sticky";
import Summary from "@/components/Summary/Summary";
import Navbar from "@/components/Navbar/Navbar";

// Import the Urbanist font
const urbanist = Urbanist({
  subsets: ["latin"], // "latin" is the correct subset
  weight: ["400", "700"], // Ensure weights exist for Urbanist
});

// Import local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900", // Variable weight for local font
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900", // Variable weight for local font
});

// Metadata for the application
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${urbanist.className} bg-bgBody`}>
        <Navbar />
        <Hero />
        <Travel />
        <Illustration1 />
        <Influencer />
        <Sticky />
        <Summary />
        {children}
      </body>
    </html>
  );
}